### ISSUE TITLE
Unable to locate executable file: sls. (sls version 3.19.0)

### ISSUE THREAD

**Issue by remithomas** [Teakowa/setup-serverless#516]
I'm getting this issue to locate the bin during a step in GithubActions.

- actions version: v2.0.0
- sls version: 3.19
- node version: 16.15.1/x64
- yarn version: 1.22.19

Here is the step definition

```yml
- uses: Teakowa/setup-serverless@v2.0.0
   with:
      provider: aws
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_REGION: ${{ secrets.AWS_REGION}}
      AWS_RDS: prod-env
```

Here is the log during the failing step

```log
Run Teakowa/setup-serverless@v2.0.0
[13](https://github.com/REPO_URL/runs/7019061342?check_suite_focus=true#step:8:14)
Installing serverless version 3.19.0 ...
[14](https://github.com/REPO_URL/runs/7019061342?check_suite_focus=true#step:8:15)
Try to restore cache...
[15](https://github.com/REPO_URL/runs/7019061342?check_suite_focus=true#step:8:16)
Received 22 of 22 (100.0%), 0.0 MBs/sec
[16](https://github.com/REPO_URL/runs/7019061342?check_suite_focus=true#step:8:17)
Cache Size: ~0 MB (22 B)
[17](https://github.com/REPO_URL/runs/7019061342?check_suite_focus=true#step:8:18)
/usr/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/ff579641-d9af-4b20-b6e3-5208b4446082/cache.tzst -P -C /home/runner/work/REPO/GITHUB_ACTION_NAME
[18](https://github.com/REPO_URL/runs/7019061342?check_suite_focus=true#step:8:19)
Cache restored successfully
[19](https://github.com/REPO_URL/runs/7019061342?check_suite_focus=true#step:8:20)
/usr/bin/tar --posix --use-compress-program zstd -T0 -cf cache.tzst -P -C /home/runner/work/REPO/GITHUB_ACTION_NAME --files-from manifest.txt
[20](https://github.com/REPO_URL/runs/7019061342?check_suite_focus=true#step:8:21)
Cache Size: ~0 MB (22 B)
[21](https://github.com/REPO_URL/runs/7019061342?check_suite_focus=true#step:8:22)
Cache saved successfully
[22](https://github.com/REPO_URL/runs/7019061342?check_suite_focus=true#step:8:23)
cacheId: 190
[23](https://github.com/REPO_URL/runs/7019061342?check_suite_focus=true#step:8:24)
Error: Unable to locate executable file: sls. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

Updates:
- it passes by using `serverless_version: 2.72.3` in arg
- it passes by using `serverless_version: 3.18.2` in arg
