### ISSUE TITLE
syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by remithomas** [Teakowa/setup-serverless#633]
I'm getting an issue in this step

```yaml
 - uses: Teakowa/setup-serverless@v2.0.0
        with:
          provider: aws
          serverless_version: 3.18.2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: ${{ secrets.AWS_REGION}}
```

it seems to be this code `syntax error near unexpected token `newline'`

```ts
Run Teakowa/setup-serverless@v2.0.0
[13](https://github.com/datagrapes/datagrapes-importer/actions/runs/3722212511/jobs/6317542772#step:8:14)
Installing serverless version 3.18.2 ...
[14](https://github.com/datagrapes/datagrapes-importer/actions/runs/3722212511/jobs/6317542772#step:8:15)
Try to restore cache...
[15](https://github.com/datagrapes/datagrapes-importer/actions/runs/3722212511/jobs/6317542772#step:8:16)
/bin/bash -c curl -o- -L https://sls-standalone-1300963013.cos.ap-shanghai.myqcloud.com/install.sh | bash
[16](https://github.com/datagrapes/datagrapes-importer/actions/runs/3722212511/jobs/6317542772#step:8:17)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[17](https://github.com/datagrapes/datagrapes-importer/actions/runs/3722212511/jobs/6317542772#step:8:18)
                                 Dload  Upload   Total   Spent    Left  Speed
[18](https://github.com/datagrapes/datagrapes-importer/actions/runs/3722212511/jobs/6317542772#step:8:19)

[19](https://github.com/datagrapes/datagrapes-importer/actions/runs/3722212511/jobs/6317542772#step:8:20)
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[20](https://github.com/datagrapes/datagrapes-importer/actions/runs/3722212511/jobs/6317542772#step:8:21)
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[21](https://github.com/datagrapes/datagrapes-importer/actions/runs/3722212511/jobs/6317542772#step:8:22)
100   481  100   481    0     0    273      0  0:00:01  0:00:01 --:--:--   273
[22](https://github.com/datagrapes/datagrapes-importer/actions/runs/3722212511/jobs/6317542772#step:8:23)
100   481  100   481    0     0    273      0  0:00:01  0:00:01 --:--:--   273
[23](https://github.com/datagrapes/datagrapes-importer/actions/runs/3722212511/jobs/6317542772#step:8:24)
bash: line 1: syntax error near unexpected token `newline'
[24](https://github.com/datagrapes/datagrapes-importer/actions/runs/3722212511/jobs/6317542772#step:8:25)
bash: line 1: `<?xml version='1.0' encoding='utf-8' ?>'
[25](https://github.com/datagrapes/datagrapes-importer/actions/runs/3722212511/jobs/6317542772#step:8:26)
Error: The process '/bin/bash' failed with exit code 2
```
