### ISSUE TITLE
[Feature Request]: Semantic version support

### ISSUE THREAD

**Issue by Teakowa** [Teakowa/setup-serverless#672]
### Is your feature request related to a problem? Please describe.

Add support for semantic version numbers, which helps users focus on their business deployments and reduces the focus on minor and fixes version.

And allows users to automatically get the latest minor and fixes version(this usually includes some security updates).

### Describe the solution you'd like

```yaml
steps:
  - uses: Teakowa/setup-serverless@v2
    with:
      serverless_version: 3.x # 3.*, 3.9.x, 2.*, 2.x, 2.71.x
      provider: aws
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}

  - run: sls deploy
```
